### ISSUE TITLE
Support for AARCH(64)-architecture

### ISSUE THREAD

**Issue by MonsterDruide1** [encounter/objdiff#60]
Well, not much else to say about it ... I'd want to try using this on a decomp project for Nintendo Switch, which uses AARCH64.

I'm currently happy with using `asm-differ`, so feel free to sort this to being a low-priority issue.

**Comment by encounter** [comment]
This would be great to add, but the current limiting factor is finding (or creating) a complete enough aarch64 disassembler in Rust. Existing options:
- [capstone](https://github.com/capstone-rust/capstone-rs): API doesn't provide enough information for formatting arguments individually, which objdiff needs in order to diff individual args. Dependency on a C library, which is a problem for compiling objdiff to WASM. (Rust and C use incompatible WASM ABIs)
- [bad64](https://github.com/yrp604/bad64): Seems to be missing formatting logic. Also a dependency on a C library.
- [disarm64](https://github.com/kromych/disarm64): Seems promising, but missing SIMD support. I assume the Switch makes use of SIMD.
- [yaxpeax-arm](https://github.com/iximeow/yaxpeax-arm): Also promising, also missing SIMD support.

Hopefully this changes in the near future, or someone works on finishing SIMD support for one of the above. I guess another question is: Would it still be useful to add ARM64 without SIMD?

**Comment by MonsterDruide1** [comment]
For automatically diffing the resulting decompiled functions, we're currently using a mix of `bad64` and `capstone`, feel free to look into that:
https://github.com/open-ead/nx-decomp-tools/blob/master/viking/Cargo.toml

I assume that SIMD would mean NEON on the Switch. It is used in some very specific functions, but not too heavily across entire games. The only occurence I came over that were not hidden deep within some math-heavy functions were matrix-multiplications, apart from those it always uses the standard floating point registers/functions. So, it would still be useful having the architecture supported without SIMD, although we couldn't use `objdiff` as full replacement for `asm-differ` then.

**Comment by MonsterDruide1** [comment]
Here's something else I ran across today:
https://github.com/emproof-com/nyxstone

This seems to provide rust bindings for disassembling any architecture supported by LLVM, which should also include AARCH64.

**Comment by encounter** [comment]
I realized `yaxpeax-arm` supports ARMv8 SIMD, so I implemented an experimental backend in 424434edd6564a6c2afaea051d8f2c43ae755d2a. This required [a lot of custom code](https://github.com/encounter/objdiff/blob/424434edd6564a6c2afaea051d8f2c43ae755d2a/objdiff-core/src/arch/arm64.rs#L192), and not a lot of relocations are handled yet, so please provide feedback if you try it!

**Comment by MonsterDruide1** [comment]
Thanks for taking care of this! It seems like I need more help setting up the project for me though, is there something like a Discord server for this to allow easier communication?

**Comment by encounter** [comment]
Yep! https://discord.gg/hKx3FJJgrV
